name: do-the-job
on: push

jobs:
  # Job to start a self-hosted EC2 runner when needed
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    steps:
      - name: Check if runner is needed
        run: |
          # Logic to determine if a runner is needed
          # For example, check the current workload or queue
          echo "Runner is needed" # Replace with your logic

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-069c334ba5dcd5d13
          ec2-instance-type: t2.micro
          subnet-id: subnet-09c3b8f8bb6ba89b3
          security-group-id: sg-04e7648cc147d15e1

  # Job to perform the actual work on the runner
  do-the-job:
    name: Do the job on the runner
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Hello World
        run: echo 'Hello World!'

  # ... Other jobs and steps

  # Job to stop the self-hosted EC2 runner when not needed
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - do-the-job # Wait when the job on the runner is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # Stop the runner even if there was an error in the job on the runner
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-
