name: do-the-job
on: push

jobs:
  # Job to start a self-hosted EC2 runner when needed
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    steps:
      - name: Check if runner is needed
        run: |
          # Logic to determine if a runner is needed
          # For example, check the current workload or queue
          # You can use GitHub API, AWS Lambda, or other mechanisms to trigger this step
          echo "Runner is needed" # Replace with your logic

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          # Other configuration settings

  # Job to perform the actual work on the runner
  do-the-job:
    name: Do the job on the runner
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Hello World
        run: echo 'Hello World!'

  # Job 2 - Add another job to run in parallel
  job2:
    name: Another parallel job
    runs-on: ubuntu-latest
    steps:
      - name: Parallel Job 2
        run: echo 'This is parallel job 2'

  # Job 3 - Add another job to run in parallel
  job3:
    name: Yet another parallel job
    runs-on: ubuntu-latest
    steps:
      - name: Parallel Job 3
        run: echo 'This is parallel job 3'

  # Job to stop the self-hosted EC2 runner when not needed
  stop-runner:
    name: Stop self-hosted EC2 runner
    runs-on: ubuntu-latest
    if: ${{ failure() || success() }} # Decide when to stop the runner
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          # Other configuration settings
